source 'https://rubygems.org'

gem 'signalwire-sdk', '~> 2.0', require: 'signalwire'
gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'
gem 'faye-websocket', '~> 0.11'
gem 'eventmachine', '~> 1.2'
gem 'thin', '~> 1.8'
